name: Rollback deployments to previous version

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Rollback Deployment to Last Stable
        run: |
          kubectl rollout undo deployment/n8n  # Rollback to the last successful deployment
          kubectl rollout undo deployment/ollama
          kubectl rollout undo deployment/qdrant
